# Backend configuration for dev environment
# Generated by init-backend.sh

bucket         = "bi8s-terraform-state-dev"
key            = "bi8s/dev/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "bi8s-terraform-locks-dev"
encrypt        = true
