#!/bin/bash
set -e

# Script to initialize Terraform/OpenTofu backend (S3 + DynamoDB)
# Usage: ./scripts/init-backend.sh <project-name> <environment> <aws-region>

# Check arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <project-name> <environment> <aws-region>"
    echo "Example: $0 bi8s dev us-east-1"
    exit 1
fi

PROJECT_NAME=$1
ENVIRONMENT=$2
AWS_REGION=$3

STATE_BUCKET="${PROJECT_NAME}-terraform-state-${ENVIRONMENT}"
LOCK_TABLE="${PROJECT_NAME}-terraform-locks-${ENVIRONMENT}"

echo "Initializing Terraform Backend"
echo "Project Name: ${PROJECT_NAME}"
echo "Environment: ${ENVIRONMENT}"
echo "AWS Region: ${AWS_REGION}"
echo "S3 Bucket: ${STATE_BUCKET}"
echo "DynamoDB Table: ${LOCK_TABLE}"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "Error: AWS CLI is not installed. Please install it first."
    exit 1
fi

# Check AWS credentials
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    echo "Error: AWS credentials are not configured properly."
    exit 1
fi

echo "AWS credentials verified."
echo ""

# Create S3 bucket for Terraform state
echo ""
echo "Creating S3 bucket: ${STATE_BUCKET}..."
if aws s3 ls "s3://${STATE_BUCKET}" 2>&1 | grep -q 'NoSuchBucket'; then
    aws s3api create-bucket \
        --bucket "${STATE_BUCKET}" \
        --region "${AWS_REGION}" \
        $(if [ "${AWS_REGION}" != "us-east-1" ]; then echo "--create-bucket-configuration LocationConstraint=${AWS_REGION}"; fi)
    
    echo "S3 bucket created successfully."
    
    # Enable versioning
    echo "Enabling versioning on S3 bucket..."
    aws s3api put-bucket-versioning \
        --bucket "${STATE_BUCKET}" \
        --versioning-configuration Status=Enabled
    
    # Enable encryption
    echo "Enabling encryption on S3 bucket..."
    aws s3api put-bucket-encryption \
        --bucket "${STATE_BUCKET}" \
        --server-side-encryption-configuration '{
            "Rules": [{
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                }
            }]
        }'
    
    # Block public access
    echo "Blocking public access on S3 bucket..."
    aws s3api put-public-access-block \
        --bucket "${STATE_BUCKET}" \
        --public-access-block-configuration \
            "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
    
    # Add lifecycle policy
    echo "Adding lifecycle policy to S3 bucket..."
    aws s3api put-bucket-lifecycle-configuration \
        --bucket "${STATE_BUCKET}" \
        --lifecycle-configuration '{
            "Rules": [{
                "Id": "DeleteOldVersions",
                "Status": "Enabled",
                "NoncurrentVersionExpiration": {
                    "NoncurrentDays": 90
                }
            }]
        }'
    
    # Add tags
    aws s3api put-bucket-tagging \
        --bucket "${STATE_BUCKET}" \
        --tagging "TagSet=[{Key=Project,Value=${PROJECT_NAME}},{Key=Environment,Value=${ENVIRONMENT}},{Key=ManagedBy,Value=Script}]"
    
    echo "S3 bucket configured successfully."
else
    echo "S3 bucket already exists."
fi

# Create DynamoDB table for state locking
echo ""
echo "Creating DynamoDB table: ${LOCK_TABLE}..."
if ! aws dynamodb describe-table --table-name "${LOCK_TABLE}" --region "${AWS_REGION}" &> /dev/null; then
    aws dynamodb create-table \
        --table-name "${LOCK_TABLE}" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "${AWS_REGION}" \
        --tags Key=Project,Value="${PROJECT_NAME}" Key=Environment,Value="${ENVIRONMENT}" Key=ManagedBy,Value=Script
    
    echo "Waiting for DynamoDB table to be active..."
    aws dynamodb wait table-exists --table-name "${LOCK_TABLE}" --region "${AWS_REGION}"
    
    # Enable point-in-time recovery
    echo "Enabling point-in-time recovery on DynamoDB table..."
    aws dynamodb update-continuous-backups \
        --table-name "${LOCK_TABLE}" \
        --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true \
        --region "${AWS_REGION}"
    
    echo "DynamoDB table created and configured successfully."
else
    echo "DynamoDB table already exists."
fi

# Create backend configuration file
BACKEND_CONFIG_FILE="infra/tofu/envs/${ENVIRONMENT}/backend-${ENVIRONMENT}.hcl"
echo ""
echo "Creating backend configuration file: ${BACKEND_CONFIG_FILE}..."
cat > "${BACKEND_CONFIG_FILE}" <<EOF
# Backend configuration for ${ENVIRONMENT} environment
# Generated by init-backend.sh

bucket         = "${STATE_BUCKET}"
key            = "${PROJECT_NAME}/${ENVIRONMENT}/terraform.tfstate"
region         = "${AWS_REGION}"
dynamodb_table = "${LOCK_TABLE}"
encrypt        = true
EOF

echo "Backend configuration file created."
echo ""
echo "Backend Initialization Complete!"
echo ""
echo "Next steps:"
echo "1. Navigate to the environment directory:"
echo "   cd infra/tofu/envs/${ENVIRONMENT}"
echo ""
echo "2. Initialize OpenTofu with the backend:"
echo "   tofu init -backend-config=backend-${ENVIRONMENT}.hcl"
echo ""
echo "3. Plan your infrastructure:"
echo "   tofu plan"
echo ""
echo "4. Apply your infrastructure:"
echo "   tofu apply"
echo ""
echo "Or use the deploy script:"
echo "   ./scripts/deploy.sh ${ENVIRONMENT} plan"
echo "   ./scripts/deploy.sh ${ENVIRONMENT} apply"
echo ""
